[package]
name = "vertx-crsf"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bitfield = "=0.19.3"
crc = "=3.3.0"
embedded-io = "=0.7.1"

[lints]
workspace = true
