[tools]
"aqua:rhysd/actionlint" = "1.7.9"
"aqua:WebAssembly/binaryen" = "125"
"aqua:biomejs/biome" = "2.3.8"
"cargo:cargo-nextest" = "0.9.114"
"cargo:cargo-shear" = "1.7.1"
"cargo:cargo-sort" = "2.0.2"
"aqua:dprint/dprint" = "0.50.2"
node = "25.2.1"
pnpm = "10.24.0"
"cargo:probe-rs-tools" = "0.30.0"
"aqua:crate-ci/typos" = "1.40.0"
"cargo:wasm-bindgen-cli" = "0.2.105"
"ubi:wetheredge/wrun" = "0.1.5"
