[tools]
actionlint = "1.7.8"
bun = "1.3.0"
dprint = "0.50.2"
typos = "1.38.1"

"cargo:cargo-nextest" = "0.9.105"
"cargo:cargo-shear" = "1.5.2"
"cargo:cargo-sort" = "2.0.2"
"cargo:probe-rs-tools" = "0.29.1"
"cargo:wasm-bindgen-cli" = "0.2.104"
"cargo:wasm-opt" = "0.116.1"

"ubi:wetheredge/wrun" = "0.1.4"
